# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=30)),
                ('classe', models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('formule_resultat', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Enfant')),
            ],
        ),
        migrations.AddField(
            model_name='dictee',
            name='classe',
            field=models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1', max_length=3, null=True),
        ),
    ]
