# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20161029_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='classe',
            field=models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1', max_length=3, null=True),
        ),
    ]
