# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_probleme_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='unite_resultat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
