# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_probleme_unite_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictee',
            name='classe',
            field=models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1A', 'CE1 A'), ('CE1B', 'CE1 B'), ('CE1C', 'CE1 C'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1C', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='classe',
            field=models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1A', 'CE1 A'), ('CE1B', 'CE1 B'), ('CE1C', 'CE1 C'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1C', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='classe',
            field=models.CharField(choices=[('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1A', 'CE1 A'), ('CE1B', 'CE1 B'), ('CE1C', 'CE1 C'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6', '6ieme')], default='CE1C', max_length=6, null=True),
        ),
    ]
