# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20161105_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleme',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
